spring:
  application:
    name: user
  profiles:
    active: ${PROFILE_ACTIVE}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8071/}
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
    discovery:
      client:
        health-indicator:
          enabled: false
#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka