apiVersion: v1
name: kube-prometheus
description: Prometheus for metrics collection, remote-writing to Grafana Cloud
type: application
version: 1.0.0
appVersion: "3.1.0"

dependencies:
  - name: prometheus
    version: "27.4.0"
    repository: https://prometheus-community.github.io/helm-charts