spring:
  application:
    name: restaurant

  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
    discovery:
      client:
        health-indicator:
          enabled: false
    stream:
      binders:
        rabbit:
          type: rabbit
        kafka:
          type: kafka
      default-binder: rabbit
      kafka:
        binder:
          brokers: ${KAFKA_HOSTNAME:localhost}:9092
      bindings:
        notification-events-out-0:
          destination: notification-events
          content-type: application/json
          binder: rabbit
        feed-events-out-0:
          destination: feed-events
          content-type: application/json
          binder: kafka
        activity-events-out-0:
          destination: activity-events
          content-type: application/json
          binder: kafka


  profiles:
    active: ${PROFILE_ACTIVE}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8071/}

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka
