spring:
  application:
    name: restaurant

  cloud:
    stream:
      bindings:
        notification-events-out-0:
          destination: notification-events
          content-type: application/json
      default-binder: rabbit

  profiles:
    active: ${PROFILE_ACTIVE}
  config:
    import: optional:configserver:http://localhost:8071/

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
