apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-prometheus.fullname" . }}
  labels:
    {{ include "kube-prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
      evaluation_interval: {{ .Values.prometheus.evaluationInterval }}

    scrape_configs:
      - job_name: 'activity'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['activity.default.svc.cluster.local:9012']

      - job_name: 'feed'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['feed.default.svc.cluster.local:9011']

      - job_name: 'list'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['list.default.svc.cluster.local:8084']

      - job_name: 'notification'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['notification.default.svc.cluster.local:9010']

      - job_name: 'restaurant'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['restaurant.default.svc.cluster.local:8085']

      - job_name: 'review'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['review.default.svc.cluster.local:8081']

      - job_name: 'social-graph'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['social-graph.default.svc.cluster.local:8083']

      - job_name: 'user'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['user.default.svc.cluster.local:8082']

      - job_name: 'gateway-server'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['gateway-server.default.svc.cluster.local:8072']

      # - job_name: 'eureka-server'
      #   metrics_path: '/actuator/prometheus'
      #   static_configs:
      #     - targets: ['eureka-server.default.svc.cluster.local:8070']

      - job_name: 'config-server'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['config-server.default.svc.cluster.local:8071']