server:
  port: 9010

spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: notification

  profiles:
    active: ${PROFILE_ACTIVE}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8071/}

  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
    discovery:
      client:
        health-indicator:
          enabled: false

    function:
      definition: notificationConsumer
    openfeign:
      circuitbreaker:
        enabled: true

    stream:
      bindings:
        notificationConsumer-in-0:
          destination: notification-events
          group: ${spring.application.name}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

    instances:
      userService:
        baseConfig: default
      restaurantService:
        baseConfig: default

  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 500ms
      restaurantService:
        maxAttempts: 3
        waitDuration: 500ms

  timelimiter:
    instances:
      userService:
        timeoutDuration: 3s
      restaurantService:
        timeoutDuration: 3s