apiVersion: 1

groups:
  - orgId: 1
    name: service-alerts
    folder: Services
    interval: 30s

    rules:
      - uid: service_down
        title: Service Down
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: up == 0
              refId: A
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          summary: "Service {{ $labels.job }} is down"
        labels:
          severity: critical