server:
  port: 9012

spring:
  application:
    name: activity

  profiles:
    active: ${PROFILE_ACTIVE}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8071/}

  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
    discovery:
      client:
        health-indicator:
          enabled: false
    function:
      definition: activityConsumer
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      bindings:
        activityConsumer-in-0:
          destination: activity-events
          group: ${spring.application.name}
          content-type: application/json
      kafka:
        binder:
          brokers:
            - ${KAFKA_HOSTNAME:localhost}:9092

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka