apiVersion: v1
kind: ConfigMap
metadata:
  name: configserver-configmap

data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.global.activeProfile }}"
  PROFILE_ACTIVE: "{{ .Values.global.profileActive }}"
  SPRING_CLOUD_CONFIG_URI: "{{ .Values.global.springCloudConfigURI }}"

  CONFIG_REPO_URL: "{{ .Values.global.configRepoUserUrl }}"
  CONFIG_REPO_USERNAME: "{{ .Values.global.configRepoUsername }}"
  CONFIG_REPO_PASSWORD: "{{ .Values.global.configRepoPassword }}"
  ENCRYPTION_KEY: "{{ .Values.global.encryptionKey }}"

  SPRING_RABBITMQ_HOST: "{{ .Values.global.rabbitMQHost }}"
  SPRING_RABBITMQ_USERNAME: "{{ .Values.global.rabbitMQUsername }}"
  SPRING_RABBITMQ_PASSWORD: "{{ .Values.global.rabbitMQPassword }}"

  JAVA_TOOL_OPTIONS: "{{ .Values.global.openTelemetryJavaAgent }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.global.otelExporterEndPoint }}"
  OTEL_METRICS_EXPORTER: "{{ .Values.global.otelMetricsExporter }}"
  OTEL_LOGS_EXPORTER: "{{ .Values.global.otelLogsExporter }}"