replicaCount: 1

image:
  repository: grafana/grafana
  tag: "11.4.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

grafana:
  adminUser: admin
  adminPassword: admin
  anonymousEnabled: true
  anonymousOrgRole: Admin

datasources:
  prometheus:
    url: http://kube-prometheus.{{ .Release.Namespace }}.svc.cluster.local:9090
  tempo:
    url: http://grafana-tempo.{{ .Release.Namespace }}.svc.cluster.local:3100
  loki:
    url: http://grafana-loki-gateway.{{ .Release.Namespace }}.svc.cluster.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
