{{- range .Values.instances }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  type: ClusterIP
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
{{- end }}