spring:
  application:
    name: list
  profiles:
    active: ${PROFILE_ACTIVE}
  config:
    import: optional:configserver:http://localhost:8071/
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      binders:
        rabbit:
          type: rabbit
        kafka:
          type: kafka
      default-binder: rabbit
      kafka:
        binder:
          brokers: ${KAFKA_HOSTNAME:localhost}:9092
      bindings:
        notification-events-out-0:
          destination: notification-events
          content-type: application/json
          binder: rabbit
        feed-events-out-0:
          destination: feed-events
          content-type: application/json
          binder: kafka
        activity-events-out-0:
          destination: activity-events
          content-type: application/json
          binder: kafka

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

    instances:
      userService:
        baseConfig: default
      restaurantService:
        baseConfig: default

  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 500ms
      restaurantService:
        maxAttempts: 3
        waitDuration: 500ms

  timelimiter:
    instances:
      userService:
        timeoutDuration: 3s
      restaurantService:
        timeoutDuration: 3s