name: Teardown Environment - Reusable Workflow

on:
  workflow_call:
    inputs:
      branch:
        description: Branch on which the build step is happening
        required: true
        type: string
      environment:
        description: Environment in which Unavu application is being deployed
        required: true
        type: string
      gate:
        description: Name of Github environment or Approval gate
        required: true
        type: string
    secrets:
      SECRETS_YAML:
        description: YAML file with the secrets for the environment
        required: true

jobs:
  Teardown_Environment:
    if: startsWith(github.ref, inputs.branch)
    runs-on: self-hosted
    environment: ${{inputs.gate}}
    steps:
        - name: Checkout Helm charts
          uses: actions/checkout@v4
          with:
            repository: KDSCRIPT/Unavu
            ref: helm
            clean: true

        - name: Tear down ${{inputs.environment}}
          env:
            SECRETS_CONTENT: ${{ secrets.SECRETS_YAML }}
          run: |
            ENV_LOWER="${{ inputs.environment }}"
            ENV_LOWER="${ENV_LOWER,,}"
            rm -f ./environments/secrets.${ENV_LOWER}.yaml
            echo "$SECRETS_CONTENT" > ./environments/secrets.${ENV_LOWER}.yaml
            cd deploy
            helmfile -e "${ENV_LOWER}" --state-values-set IMAGE_TAG="${{ github.sha }}" destroy
